### ISSUE TITLE
구장별 날씨 정보 제공

### ISSUE THREAD

**Issue by innerstella** [innerstella/happybaseball-diary#14]
# TODO

## 자료 정리

- [x] 구장별 x, y 좌표 정리

## 개발

- [x] 구장 스와이프
- [x] 구장별 좌표 연결
- [x] 1시간 후, 2시간 후, 3시간 후 날씨 정보 표시
- [x] 기준 시간 표시
- [x] 기상청 출처 표시
- [x] 현재 기온 표시
- [x] 현재 하늘 상태 아이콘 표시

## UX

- [x] 로딩 스피너
- [x] 스켈레톤
- [x] 디자인 정리

# DESIGN
<img width="383" alt="image" src="https://github.com/innerstella/happybaseball-diary/assets/77491430/b6ef53ba-83a9-4471-adc4-891d9f00de9c">

**Comment by innerstella** [comment]
https://www.findlatlng.org/

**Comment by innerstella** [comment]
https://fronteer.kr/service/kmaxy
